#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Apr 26, 2019 08:30:18 PM IST  platform: Windows NT

import sys
from threading import Thread
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import unknown.py
    unknown.py.vp_start_gui()

def search():
    print("Search pressed")
    try:
        s=w.Entry1.get()
        #running on a new thread, main thread will crash! 
        t1=Thread(target=startProcess, args=(s,))
        t1.start()
    except Exception as e:
        print("An error occured: "+e)

def startProcess(term):
    from search import scrape
    
    print("Looking for : "+term)
    searching()

    try:
        results = scrape(term)
        #print(results)

        insertToList(results)
        stopsearching()
    except Exception as e:
        results=[]
        results.append("Please enter a valid search" + str(e))
        insertToList(results)
def searching():
    w.Button1["text"]="Searching.."
    
def stopsearching():
    w.Button1["text"]="Search.."

def insertToList(links):
    w.Listbox1.delete(0,tk.END)
    for link in links:
        w.Listbox1.insert(tk.END,str(link))

def pressPPT():
    #print(str(w.Listbox1.get(tk.ACTIVE)))
    url=str(w.Listbox1.get(tk.ACTIVE))
    print(url)
    try:
        startLoading()
        t1=Thread(target=makePPT,args=(url,))
        t1.start()
    except Exception as e:
        print(str(e))

def startLoading():
    w.Button3["text"]="Loading.."
    w.Button3["state"]=tk.DISABLED

def stopLoading():
    w.Button3["text"]="Open"
    w.Button3["state"]=tk.NORMAL

def makePPT(url):
    if(len(url.strip())>0):
        url=url[url.rfind('||')+2:len(url)]
        url=url.strip()
        print("Extracted : "+ url)
        
        from instant_ppt import tt, savePPT
        results=tt(url)

        s=url[(url.rfind('/')+1):len(url)]
        savePPT(results,s)
        stopLoading()
    else:
        print("Nothing selected... not doing anything..")

def clickOpen():
    print("Opening..")
    filename="output.pptx"
    try:
        t1=Thread(target=openFile,args=(filename,))
        t1.start()
    except Exception as e:
        print(str(e))

def openFile(filename):
    try:
        import os
        if(os.path.exists(filename)):
            os.system("start "+filename)
        else:
            print("File doesn't exists")
    except Exception as e:
        print(str(e))    






